builders:
  alphax_generator:
    import: "package:alphax_generator/builder.dart"
    builder_factories: ["alphaxBuilder"]
    build_extensions: {".dart": [".alphax_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
